---
title: "Aula 02 - Slide 14: ACF e PACF"
output: html_document
---

## Objetivo
Gerar ACF e PACF para uma serie AR(1) e ilustrar dependencias temporais.

## Conexao com o PDF
Slide 14 do PDF `02-Estrutura-Temporal-em-Series-Temporais.pdf`, arquivos de saida `slides/02-14a.png`, `slides/02-14b.png` e `slides/02-14.png`.

## Descricao do codigo
Simula um AR(1), plota ACF e PACF em arquivos separados e os concatena.

```{r setup, message=FALSE, warning=FALSE}
source("https://raw.githubusercontent.com/eogasawara/series-temporais/main/code/utils.R")
set.seed(214)
```

```{r gerar-figura}
n <- 300
x <- arima.sim(model = list(ar = 0.7), n = n)

# (a) ACF
fa <- har_slide_file("02", "14", "a")
grDevices::png(fa, width = TSED_WIDTH, height = TSED_HEIGHT, res = TSED_DPI)
stats::acf(x, main = "ACF: dependencia temporal AR(1)")
grDevices::dev.off()

# (b) PACF
fb <- har_slide_file("02", "14", "b")
grDevices::png(fb, width = TSED_WIDTH, height = TSED_HEIGHT, res = TSED_DPI)
stats::pacf(x, main = "PACF: assinatura do AR(1)")
grDevices::dev.off()

# Composicao final do slide
out <- har_slide_file("02", "14")
har_concat_png(out, c(fa, fb))
```
